services:

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"