services:

  client:
    container_name: docs-client
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    volumes:
        - ./client:/app
        - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    depends_on:
      - server
    restart: always

  server:
    container_name: docs-server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: docs-mongo
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: